### ISSUE TITLE
Lint is throwing errors

### ISSUE THREAD

**Issue by drgrigg** [irontigran/john-w-campbell_islands-of-space#14]
Could you look at these? Mostly they are about spurious `<hr/>` tags at the end of each chapter. Please remove these.

The others are to do with punctuation which should be within quotes not outside of it.

**Comment by drgrigg** [comment]
Also if there's an endnotes file you need to attribute the annotations (usually the author or editor) in content.opf

**Comment by irontigran** [comment]
My apologies - I didn't see the lint errors because I hadn't upgraded to v1.1.0 of the toolset yet.

**Comment by irontigran** [comment]
> The others are to do with punctuation which should be within quotes not outside of it.

I've manually checked the punctuation errors that lint is showing - they're all of the following form (example from chapter 9):

> ... he worked at drawing the "note".

So, it's a word or phrase enclosed in quotation marks to show some kind of emphasis, followed by punctuation. It seems to me that it's correct for the punctuation to stay outside of the quotation marks in these cases (?)

**Comment by drgrigg** [comment]
Personally I agree with you, as that's British usage. But American usage seems to be to put the punctuation into the quotes regardless.

**Comment by irontigran** [comment]
Fixed the punctuation marks here: 83cd677af3dd9b7a92e2a8449856daf69b39e199

For the annotations - who should the annotator be? The book was originally published in a magazine and then edited for publication in book form later. Do I attribute the endnote to the editor for the book ([Wikipedia](https://en.wikipedia.org/wiki/Islands_of_Space) says Lloyd Eshbach) or someone else?

**Comment by drgrigg** [comment]
Good question. Since we don't really know, it's safe to leave out the 'ann' attribution from content.opf. You can safely ignore the lint warning in such cases.
