### ISSUE TITLE
Prologue isn't frontmatter

### ISSUE THREAD

**Issue by drgrigg** [irontigran/john-w-campbell_islands-of-space#15]
Looking at the prologue here, it's wrongly attributed as frontmatter. But it's clear that in this book it's part of the story, not something like an introduction or preface or author's note. So it should be marked as bodymatter, and you don't need a half-title page.

**Comment by drgrigg** [comment]
You'll need to re-run print-toc after fixing this.

**Comment by irontigran** [comment]
Fixed: e56170cdd461d8961fa7d352d3e977d79730835d
