### ISSUE TITLE
Unsemanticated italics

### ISSUE THREAD

**Issue by drgrigg** [irontigran/john-w-campbell_islands-of-space#16]
This is really just my opinion, but I think that lux (as in 'lux metal') should either not be italicised at all, which is probably preferable, or else given a Latin language tag, eg `<i xml:lang="la">lux</i>`. 

I think I would remove all the italics around lux (and relux) EXCEPT for the one instance where they are referring to the origin of the word from Latin ("Lux is the Latin for light") and give it the above language tag.

This one is OK, leave it: `to the <i>n</i>th degree`

But I would semanticate the reference to The Black Star Passes in the endnotes:

See `<i epub:type="se:name.publication.book">The Black Star Passes</i>`

**Comment by irontigran** [comment]
I'll defer to your opinion on the (non-) italicization of lux, with the caveat that the current use of italics mirrors the page scans at HathiTrust.
If that doesn't make a difference, then I'll change the semantication/markup of lux as you described.

**Comment by drgrigg** [comment]
I think I'd take out the italics anyway. But it is only my opinion and we can refer this to Alex if you have a strong feeling about it.

**Comment by irontigran** [comment]
I don't feel that strongly about it - just checking that it didn't make a difference that the page scans had a specific italicization scheme.

Endnote sematication here: 6e40ffdb26ab9806d7066f1d9a1bf017bc3ad99a
Changes to lux italicization here: 103115796405aaf30ab8bb4b0b87ebccf10a9a9c
