### ISSUE TITLE
Divs around <hr/> unnecessary

### ISSUE THREAD

**Issue by drgrigg** [irontigran/john-w-campbell_islands-of-space#17]
You have a couple of instances like this:

```
			<div>
				<hr/>
			</div>
```
Please remove the `<div>` and `</div>` tags.

**Comment by irontigran** [comment]
Regarding the divs and issue #14 - should I be removing all `<hr/>` tags except the ones encapsulated in divs? So this:
```
<div>
<hr/>
</div>
```
becomes this:
```
<hr/>
```
and any `<hr/>` tags on their own get deleted.

**Comment by drgrigg** [comment]
Well, certainly the `<hr/>` tags aren't needed at the end of each chapter. And if the 'inter-scene' ones are all within divs, then leave the `<hr/>` but remove the surrounding div tags, which aren't necessary.

**Comment by irontigran** [comment]
Gotcha - updates here: 77d60e6c1fef2ce35eb66f5f2e84dfbddf78240e
