### ISSUE TITLE
Short description needs to be more generic

### ISSUE THREAD

**Issue by drgrigg** [irontigran/john-w-campbell_islands-of-space#20]
Our style is for the short description to be quite generic and not to include character names, and certainly it shouldn't refer to a previous book.

It could be something like: (I haven't read the book, though!!)

"Three friends travel the galaxy, have many fantastic adventures and explore many unusual planets."

**Comment by drgrigg** [comment]
The long description is OK, but it's a pity we haven't produced The Black Star Passes to which it refers. Is that not out of copyright?

**Comment by irontigran** [comment]
Yes, it is, as well as the third book in the trilogy, Invaders From the Infinite. It's not on the wanted list though, so when I semi-randomly grabbed a book to produce, I picked this one without realizing it was part of series. Once this one's finished, I might grab The Black Star Passes next, as well as Invaders From the Infinite (time allowing).

**Comment by irontigran** [comment]
Fixed short description here ae43db71f90f000b6f415df7102e3b0849a1874b

**Comment by drgrigg** [comment]
Excellent.
